"""change outbox message column type to jsonb

Revision ID: 27eaced8c5d8
Revises: 555a33235287
Create Date: 2026-08-09 21:48:23.650008

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "27eaced8c5d8"
down_revision: Union[str, Sequence[str], None] = "555a33235287"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE outbox ALTER COLUMN message TYPE JSONB USING message::jsonb"
    )
    op.alter_column("outbox", "message", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE outbox ALTER COLUMN message TYPE VARCHAR(2048) USING message::text"
    )
    op.alter_column("outbox", "message", nullable=False)
    # ### end Alembic commands ###
