"""add outbox table

Revision ID: 555a33235287
Revises: 8b676e93c8df
Create Date: 2026-08-08 19:53:29.751690

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "555a33235287"
down_revision: Union[str, Sequence[str], None] = "8b676e93c8df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox",
        sa.Column("topic", sa.String(length=512), nullable=False),
        sa.Column("message", sa.String(length=2048), nullable=False),
        sa.Column(
            "event_date",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "sent", name="event_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("outbox")
    op.execute("DROP TYPE IF EXISTS event_status;")
    # ### end Alembic commands ###
