"""add tags table

Revision ID: c237a3caa1ac
Revises: cde50160235e
Create Date: 2026-08-26 16:00:57.287138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c237a3caa1ac'
down_revision: Union[str, Sequence[str], None] = 'cde50160235e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('\n            LENGTH(name) >= 3\n            AND LENGTH(name) <= 25\n            ', name=op.f('ck_tags_length_tag_name')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_tags_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    # ### end Alembic commands ###
