"""increase file max size

Revision ID: cde50160235e
Revises: 27eaced8c5d8
Create Date: 2026-08-26 13:30:10.055978

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cde50160235e"
down_revision: Union[str, Sequence[str], None] = "27eaced8c5d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_files_value_size"), "files", type_="check")
    op.create_check_constraint(
        "value_size",
        "files",
        """
                size > 0
                AND size <= 20 * 1024 * 1024
                """,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_files_value_size"), "files", type_="check")
    op.create_check_constraint(
        "value_size",
        "files",
        """
                size > 0
                AND size <= 1 * 1024 * 1024
                """,
    )
    # ### end Alembic commands ###
